config/routes.rb
Bugtracker::Application.routes.draw do
  resources :priorities

  resources :statuses

  devise_for :users

  resources :bugs

  root to: 'bugs#index'

end

app/models/bug.rb
class Bug < ActiveRecord::Base
  belongs_to :user
  belongs_to :priority
  belongs_to :status
 



end

app/models/priority.rb
class Priority < ActiveRecord::Base

  attr_accessible :name
  has_many :bugs
 
  
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :bugs
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :first_name, :last_name

  has_many :bugs

  #def full_name
  #  first_name " + " last_name
  #end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  # GET /bugs
  # GET /bugs.json
  def index
    @bugs = Bug.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bugs }
    end
  end
  

  # GET /bugs/1
  # GET /bugs/1.json
  def show
    @bug = Bug.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bug }
    end
  end

  # GET /bugs/new
  # GET /bugs/new.json
  def new
    @bug = Bug.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bug }
    end
  end

  # GET /bugs/1/edit
  def edit
    @bug = Bug.find(params[:id])
  end

  # POST /bugs
  # POST /bugs.json
  def create
    @bug = Bug.new(params[:bug])

    respond_to do |format|
      if @bug.save
        format.html { redirect_to @bug, notice: 'Bug was successfully created.' }
        format.json { render json: @bug, status: :created, location: @bug }
      else
        format.html { render action: "new" }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bugs/1
  # PUT /bugs/1.json
  def update
    @bug = Bug.find(params[:id])

    respond_to do |format|
      if @bug.update_attributes(params[:bug])
        format.html { redirect_to @bug, notice: 'Bug was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bugs/1
  # DELETE /bugs/1.json
  def destroy
    @bug = Bug.find(params[:id])
    @bug.destroy

    respond_to do |format|
      format.html { redirect_to bugs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/priorities_controller.rb
class PrioritiesController < ApplicationController
  # GET /priorities
  # GET /priorities.json
  def index
    @priorities = Priority.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @priorities }
    end
  end

  # GET /priorities/1
  # GET /priorities/1.json
  def show
    @priority = Priority.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @priority }
    end
  end

  # GET /priorities/new
  # GET /priorities/new.json
  def new
    @priority = Priority.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @priority }
    end
  end

  # GET /priorities/1/edit
  def edit
    @priority = Priority.find(params[:id])
  end

  # POST /priorities
  # POST /priorities.json
  def create
    @priority = Priority.new(params[:priority])

    respond_to do |format|
      if @priority.save
        format.html { redirect_to @priority, notice: 'Priority was successfully created.' }
        format.json { render json: @priority, status: :created, location: @priority }
      else
        format.html { render action: "new" }
        format.json { render json: @priority.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /priorities/1
  # PUT /priorities/1.json
  def update
    @priority = Priority.find(params[:id])

    respond_to do |format|
      if @priority.update_attributes(params[:priority])
        format.html { redirect_to @priority, notice: 'Priority was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @priority.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /priorities/1
  # DELETE /priorities/1.json
  def destroy
    @priority = Priority.find(params[:id])
    @priority.destroy

    respond_to do |format|
      format.html { redirect_to priorities_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  def list
	@statuses = Status.find(:all)
  end
  
  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = Status.find(params[:id])

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/priorities_helper.rb
module PrioritiesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/bugs/_form.html.erb
<%= simple_form_for(@bug, html: { class: "form-horizontal" } ) do |f| %>
  <% if @bug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bug.errors.count, "error") %> prohibited this bug from being saved:</h2>

      <ul>
      <% @bug.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.input :user_id, collection: User.all, label_method: :first_name %>

    <%= f.input :priority_id, collection: Priority.all, label_method: :name %>

    <%= f.input :status_id, collection: Status.all, label_method: :name %>

    <%= f.input :description, :input_html => { :rows => 5 } %>

    <%= f.input :details, :input_html => { :rows => 5 } %>

    <div class="form-actions">
        <%= f.button :submit %>
    </div>

<% end %>

app/views/bugs/edit.html.erb
<h1>Editing bug</h1>

<%= render 'form' %>

<%= link_to 'Details', @bug, class: "btn btn-primary" %>
<%= link_to 'Back', bugs_path, class: "btn btn-primary" %>

app/views/bugs/index.html.erb
<div class="page-header">
<h1>All Bugs</h1>
</div>



<table class="table table-bordered">
  <tr>
    <th>Bug No</th>
    <th>Assigned to</th>
    <th>Status</th>
    <th>Priority</th>
    <th>Description</th>
    <th>Details</th>
    <th>Created</th>
    <th>Action</th>
  </tr>

<% @bugs.each do |bug| %>
  <tr>
    <td><%= bug.id %></td>
    <td><%= bug.user.first_name %></td>   
	<td><%= bug.status.name %>
    <td><%= bug.priority.name %></td>
    <td><%= bug.description %></td>
    <td><%= bug.details %></td>
    <td><%= time_ago_in_words(bug.created_at) %></td>
    <td><%= link_to 'Edit', edit_bug_path(bug), class: "btn btn-primary" %>
    <%= link_to 'Delete', bug, class: "btn btn-primary", confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

    <div class="form-actions">
        <%= link_to 'New Bug', new_bug_path, class: "btn btn-primary" %>
    </div>

app/views/bugs/new.html.erb
<h1>New bug</h1>

<%= render 'form' %>

<%= link_to 'Back', bugs_path, class: "btn btn-primary" %>

app/views/bugs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Assigned to:</b>
  <%= @bug.user.first_name %>
</p>

<p>
  <b>Reported by:</b>
  <%= @bug.reported_by %>
</p>

<p>
  <b>Description:</b>
  <%= @bug.description %>
</p>

<p>
  <b>Details:</b>
  <%= @bug.details %>
</p>


<%= link_to 'Edit', edit_bug_path(@bug), class: "btn btn-primary" %>
<%= link_to 'Back', bugs_path, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">

<head>
  <title>Bugtracker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>


<body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">

            <ul class="nav nav-pills">

              <li><%= link_to "All Bugs", bugs_path %></li>
              <li><%= link_to "My Queue", bugs_path %></li>

            </ul>
          <ul class="nav pull-right">
            <% if user_signed_in? %>
                <li><%= link_to current_user.first_name, edit_user_registration_path %></li>
                <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
                <li><%= link_to "Login", new_user_session_path %></li>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <% end %>
          </ul>


        </div>
      </div>
    </div>

        <div class="container">
            <p class="notice"><% notice %></p>
            <p class="alert"><% alert %></p>
            <%= yield %>
        </div>

</body>
</html>

app/views/priorities/_form.html.erb
<%= simple_form_for(@priority) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :priority %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/priorities/edit.html.erb
<h1>Editing priority</h1>

<%= render 'form' %>

<%= link_to 'Show', @priority %> |
<%= link_to 'Back', priorities_path %>

app/views/priorities/index.html.erb
<h1>Listing priorities</h1>

<table>
  <tr>
    <th>Priority</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @priorities.each do |priority| %>
  <tr>
    <td><%= priority.name %></td>
    <td><%= link_to 'Show', priority %></td>
    <td><%= link_to 'Edit', edit_priority_path(priority) %></td>
    <td><%= link_to 'Destroy', priority, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Priority', new_priority_path %>

app/views/priorities/new.html.erb
<h1>New priority</h1>

<%= render 'form' %>

<%= link_to 'Back', priorities_path %>

app/views/priorities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Priority:</b>
  <%= @priority.priority %>
</p>


<%= link_to 'Edit', edit_priority_path(@priority) %> |
<%= link_to 'Back', priorities_path %>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<h1>Listing statuses</h1>

<table>
  <tr>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @statuses.each do |status| %>
  <tr>
    <td><%= status.name %></td>
    <td><%= link_to 'Show', status %></td>
    <td><%= link_to 'Edit', edit_status_path(status) %></td>
    <td><%= link_to 'Destroy', status, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Status', new_status_path %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status:</b>
  <%= @status.name %>
</p>


<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>